# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cash',
            field=models.FloatField(default=1.0),
        ),
    ]
