# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170308_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(default='', upload_to='/images/'),
        ),
    ]
