# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, default='', upload_to='/media/'),
        ),
    ]
