# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etrade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbuy',
            name='paper_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='etrade.Paper'),
        ),
        migrations.AlterField(
            model_name='ordersell',
            name='paper_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='etrade.Paper'),
        ),
    ]
