# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrade', '0002_auto_20170303_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbuy',
            name='sport',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ordersell',
            name='sport',
            field=models.CharField(default='', max_length=255),
        ),
    ]
