# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrade', '0004_orderexecuted_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperbank',
            name='db_type',
            field=models.CharField(default='BANK', max_length=255),
        ),
    ]
