# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrade', '0005_paperbank_db_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperbank',
            name='paper_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
