# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrade', '0006_paperbank_paper_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='last_transaction',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
