# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrade', '0010_auto_20170308_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbuy',
            name='order_initial_qty',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='ordersell',
            name='order_initial_qty',
            field=models.IntegerField(default=10000),
        ),
    ]
